language: java


sudo: required
env: 
  global:
    - secure: "YPiNhz2FylPtxnlDcI7Mv5UCXmDct0m8lARIshhuic9ysBXQlP2SKEuBoOKFS5BEoL7vqvt+etdfDDF2xEpWn0fjhbc5tE+qNx/ElAQVJEnjjjiWikTobMAOb2lzpUcV9hhkENzuCcSEu9qP7LdzSY1X2KrNsc2zoAMOdCxUo5KFWvJcDcgapPdJ6pjbyCjI+90JB145/cYHmWjrBdPSMpPnsLZwgLaj/4rW0QgwyO6m0Rp3dUq/8t1dGQR0WktHdIhu2P+Dh4nieNdmzSzo/iOpXGYUvLHERIVgI9OuCzUpt47BXlU2mBKP6PUPpi3ajpVi6AEb2fjNRCFXfgu0bTgh3PYEjIoPoEb800b8yBhSrbBZgRiVTCw9g7bBmn5Kq3KdpNBDGdH1KPU2/4hd+Wbl8vZhCOXrBUWtrYLmcSmDGBUPO+yG/fR5IrxX6LWK7xDi4HDKXP2jwyKf12EMbsVq+K/7GOPMyJ+0NRt/+Eln8qod6YAxrWVbcf7h4fO/9IfZAxwS42YuKvqrf7j8O83DQ0QbqYDDWlWmZVLWlG7sEpvKWwAz4gtJ17X20rACCxjsRrAB9uTF3+NDNZO7Wca+Ol1MfgGgVwjkp8CUYP8a3S1l6buzV75AtAKYdOZWZcX8wD3XZzjEa7qxUiOUXCoFLBy3JuewVxKq7SYIvP8="

script:
  - /bin/true

after_success:
  - |
    if ([ ! -z "$TRAVIS_TAG" ]) && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      # Generate CHANGELOG.md
      gem install github_changelog_generator
      echo "Using GitHub token: ${CHANGELOG_GITHUB_TOKEN}"
      github_changelog_generator -t ${CHANGELOG_GITHUB_TOKEN}

      # Commit and push the CHANGELOG
      git config --global user.email "builds@travis-ci.com"
      git config --global user.name "Travis CI"
      git add CHANGELOG.md
      git commit -m "Add CHANGELOG [ci skip]" && git push

      # mvn deploy to Bintray
      echo "Deploy to Bintray..."

      # Create GitHub release
      release_name=="${TRAVIS_TAG:1}"
      github_changelog_generator -t ${CHANGELOG_GITHUB_TOKEN} -o /tmp/CHANGELOG.md --since-tag ${TRAVIS_TAG}
      release_changelog=$(< /tmp/CHANGELOG.md)
      curl -i -H 'Authorization: token 0438df058dc72698c966f912779bfec21eb741d5' \
        -d '{
          "tag_name": "${TRAVIS_TAG}",
          "name": "${release_name}",
          "body": "${release_changelog}",
          "draft": true,
          "prerelease": false
        }' \
        https://api.github.com/repos/donovanmuller/test-minishift-travis/releases
    else
      echo "This will not deploy!"
    fi