language: java


sudo: required
env: 
  global:
    - secure: "e4uMh+z1TIX1qAIulkyyfWrQqYY1954XYDnnwWADzdCZNOBFaS4fgt1jvoaY+zwNsoSGDdd0UAprbIu/S8tIj8LgBC6pNYOVioEGHRlFQAA5ZSaY4QSZigr/7poo2x44tUdfGjj+IaHtAy6dJxni++u0oZc4kPLzjRbNUO1QldtxnLc0utM3UsDWvdNqemrzu0x52zPCnvkjtzGwPIntkIEa5UW3+xURbVXuq++O4kiWlR7GXtPdMR7ck6LlJzOSBEYam0pwK3UzUq1uDIzUmvEyz8mSscbjkBVapI1HaVqFZJMMMC/nnV5O18mL+cHJd8OaqDR7+YeqwzXwtCjTASMnZVElweWA0Hs404NfcfzUNowrokqihE2sjOzBth0WKx9l4KijICj+PvRSr3mgAQ8/5rK2ATezDNjHdA7exXxNqpC1E0ImW+PPqYALdiIl55LhZtrVTbe4NwxRa5+XN+q3L9hJni6MhrSO35DgmsM4b5voPIr0o+njze/wReqHz83ZhMfKxHTbRZ/eVJ81aM1Lb9s7idpsiEdPB6ipfzhaZlaR62u+n4LqQ1kpc6DDZxHD9I5Ag8zFxQE7EDorhweLFHhQY82a37gdopx4+gql/CwXG+K4jI5hORxT33a8S0MlXg3svkQjr+WSitQqG8TLnPCofh2ykD5mTjAKC/A="
    - secure: "L7wBPH5bt+EFoO/jbCx8gV13HP9O3dotBrPVL6eYeN938RvrDoefkRV4hc68ijOM9NwdRPptwU+g9YeRm/HSQvH3IPcgVPWRgdnM9SSqI7tNsoQZexaqoruUPgOAkxQTHIE7lsW/u13PL1qZC1aLBmHu5w9TQ9SQPPKVwyxzMbWApftDgfmawsPsewtqx1sMixyEp0x40PhQ2lviqfLW/aLLdS9rLsjQVBJL5nFYBSNBnYyc2QIuDt9b+dDyTsMJVIetNUcpnnvWdwpQsMyH2+wcPzY5rB/DrcQYrguqgI3Wn2jiEueIYWHNsWEa1K7XN+RfqG2qrzQJlW76yt6D4uZcwIDODKU6kK0M+qY6+Z2zAI6aw3m4pVI9FCPXvUrhT1G1ofUDXpSht4RzycYRDm8zE6jhjgQbzfB6PND42cLKUG++czNP0AR8sSNijGN7bY0LaHRbMyC+GK2vgprZZV+WOUMGn4GGA5Bt5cUbcXvdNyvbcotrEztqIs7p1WBiwzO9MM5Nvfrxxbrq/y7olwkXgbGtR2V8cGd5PT1QoGLk/rm/RSft+CcMHsoiXdcjXp1Nd5jkj2CPNnyHUEboMNhTfYWFMyPqHHUcJLYuho2OHq30KhiRf2726tJiqRukrDudEHtkzDzUz+W9EhNSyConLSFrMOagqbj7nJjwqdA="

script:
  - /bin/true

after_success:
  - |
    if ([ ! -z "$TRAVIS_TAG" ]) && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      # mvn deploy to Bintray
      echo "Deploy to Bintray..."

      # Create GitHub release
      release_name="${TRAVIS_TAG:1}"
      github_changelog_generator -t ${GITHUB_ACCESS_TOKEN} -o /tmp/CHANGELOG.md --since-tag ${TRAVIS_TAG}
      release_changelog=$(< /tmp/CHANGELOG.md)
      jq -n \
        --arg tag_name "$TRAVIS_TAG" \
        --arg release_name "$release_name" \
        --arg release_changelog "$release_changelog" \
        '{
            "tag_name": $tag_name,
            "name": $release_name,
            "body": $release_changelog,
            "draft": false,
            "prerelease": false
        }' |
        curl -i \
          -u donovanmuller:${GITHUB_ACCESS_TOKEN} \
          -d@- \
          https://api.github.com/repos/donovanmuller/test-minishift-travis/releases

      # Generate CHANGELOG.md
      gem install github_changelog_generator
      github_changelog_generator -t ${GITHUB_ACCESS_TOKEN}

      # Commit and push the CHANGELOG
      git config --global user.email "builds@travis-ci.com"
      git config --global user.name "Travis CI"
      git remote rm origin
      git remote add origin https://user:${GITHUB_ACCESS_TOKEN}@github.com/donovanmuller/test-minishift-travis.git      
      git add CHANGELOG.md
      git commit -m "Add CHANGELOG [ci skip]" && git push origin HEAD:master          
    else
      echo "This will not deploy!"
    fi